// Prix et données techniques des peintures RUCO utilisées à l'atelier.
//
// Source : factures RUCO (prix HT réellement payés, COV comprise) et fiches
// techniques (ratios 2K, dilutions, rendements). Les valeurs proviennent du
// calculateur monté sous Numbers puis en HTML autonome — voir le dossier
// « 17. Atelier / 05. RUCO » sur kDrive.
//
// ── Trois règles héritées de ce travail, à ne pas défaire ────────────────────
//
// 1. Un prix inconnu vaut `null`, JAMAIS 0. Un produit facturé à 100 % de
//    rabais n'a pas un prix catalogue de zéro : il a un prix qu'on ignore.
// 2. Les données de pulvérisation sont celles du GODET GRAVITÉ (procédé de
//    l'atelier : pistolet HVLP). Les valeurs Airmix et Airless des fiches
//    techniques ne doivent pas entrer ici.
// 3. `dilRetenue` est une hypothèse de chiffrage d'Amazing Lab, choisie dans la
//    plage de la fiche technique — pas une valeur imposée par RUCO. La dilution
//    réelle dépend de la viscosité, de la température, de la teinte et du pot.
//
// `ref` est le SKU RUCO : c'est lui qui relie ce tarif au catalogue technique
// de public/ruco/products.json, et donc le sélecteur au calculateur.

export const PEINTURES = [
  {
    ref: '180150014-580',
    nom: 'MAGISTRATOR vernis incolore mat',
    type: '1K eau',
    prixA: 20.69,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.15, dilMax: 0.2,
    densite: 1.02,
    rendMin: 7, rendMax: 9, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pulvérisation : 10–20 % à l’eau ; 15 % retenu pour le chiffrage.',
  },
  {
    ref: '120400000-052',
    nom: 'MAGISTRATOR NOVA satiné teinté 1 kg',
    type: '1K eau',
    prixA: 29.5,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.1, dilMax: 0.15,
    densite: 1.3,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : jusqu’à env. 15 % à l’eau ; 10 % retenu pour le chiffrage.',
  },
  {
    ref: '120400000-056',
    nom: 'MAGISTRATOR NOVA satiné teinté 5 kg',
    type: '1K eau',
    prixA: 24.8,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.1, dilMax: 0.15,
    densite: 1.3,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : jusqu’à env. 15 % à l’eau ; 10 % retenu pour le chiffrage.',
  },
  {
    ref: '120530000-052',
    nom: 'MAGISTRATOR Futura mat-satiné teinté 1 kg',
    type: '1K eau',
    prixA: 27.7,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.1, dilMax: 0.15,
    densite: 1.33,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Dilution à l’eau ; taux de chiffrage fixé à 10 % pour pulvérisation.',
  },
  {
    ref: '120530000-056',
    nom: 'MAGISTRATOR Futura mat-satiné teinté 5 kg',
    type: '1K eau',
    prixA: 26.38,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.1, dilMax: 0.15,
    densite: 1.33,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Dilution à l’eau ; taux de chiffrage fixé à 10 % pour pulvérisation.',
  },
  {
    ref: '120540000-052',
    nom: 'MAGISTRATOR Optima mat teinté',
    type: '1K eau',
    prixA: 35.0,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'Eau', prixDiluant: 0,
    dilMin: 0, dilRetenue: 0.1, dilMax: 0.15,
    densite: 1.3,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Dilution à l’eau ; taux de chiffrage fixé à 10 % pour pulvérisation.',
  },
  {
    ref: '126040/126020-052',
    nom: 'ATAPUR 2000 mat/satiné teinté 1 kg',
    type: '2K solvant',
    prixA: 47.94,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.3, dilRetenue: 0.5, dilMax: 0.7,
    densite: 1.15,
    rendMin: 7, rendMax: 9, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Godet gravité, buse 1,8 mm : 30–70 % V-15. 50 % retenu = milieu de la plage technique.',
  },
  {
    ref: '126040000-056',
    nom: 'ATAPUR 2000 mat teinté 5 kg',
    type: '2K solvant',
    prixA: 42.48,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.3, dilRetenue: 0.5, dilMax: 0.7,
    densite: 1.15,
    rendMin: 7, rendMax: 9, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Godet gravité, buse 1,8 mm : 30–70 % V-15. 50 % retenu.',
  },
  {
    ref: '126020050-670',
    nom: 'ATAPUR 2000 satiné blanc 5 kg',
    type: '2K solvant',
    prixA: 30.15,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.3, dilRetenue: 0.5, dilMax: 0.7,
    densite: 1.15,
    rendMin: 7, rendMax: 9, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Godet gravité, buse 1,8 mm : 30–70 % V-15. 50 % retenu.',
  },
  {
    ref: '186100008-410',
    nom: 'ATAPUR en 2 couches nature 0',
    type: '2K solvant',
    prixA: 26.18,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.1, dilRetenue: 0.15, dilMax: 0.2,
    densite: 0.9,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : 10–20 % V-15. 15 % retenu = milieu de plage.',
  },
  {
    ref: '186080008-410',
    nom: 'ATAPUR en 2 couches 10 mat 1 kg',
    type: '2K solvant',
    prixA: 25.94,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.1, dilRetenue: 0.15, dilMax: 0.2,
    densite: 0.9,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'À confirmer',
    notes: 'Dilution reprise de la famille ATAPUR 2 couches : 10–20 % V-15 ; rendement à confirmer sur FT spécifique.',
  },
  {
    ref: '186070008-670',
    nom: 'ATAPUR 2 couches 20 mat-satiné 5 kg',
    type: '2K solvant',
    prixA: 21.75,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: 0.1, dilRetenue: 0.15, dilMax: 0.2,
    densite: 0.9,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'À confirmer',
    notes: 'Dilution reprise de la famille ATAPUR 2 couches : 10–20 % V-15 ; rendement à confirmer sur FT spécifique.',
  },
  {
    ref: '186630014-550',
    nom: 'RUCOPUR vernis E+I mat 3 kg + DD5000',
    type: '2K solvant',
    prixA: 34.16,
    durcisseur: 'DD 5000', prixDurcisseur: 39.8,
    ratioA: 3, ratioB: 1,
    diluant: 'V-17', prixDiluant: null,
    dilMin: 0.05, dilRetenue: 0.075, dilMax: 0.1,
    densite: 1.02,
    rendMin: 6, rendMax: 7, rendUnite: 'm²/L',
    statut: 'Complet - prix diluant manquant',
    notes: 'Godet : 5–10 % V-17. 7,5 % retenu. Prix V-17 non trouvé dans les factures fournies.',
  },
  {
    ref: '186630014-550',
    nom: 'RUCOPUR vernis E+I mat 3 kg + PU5000 rouleau',
    type: '2K solvant',
    prixA: 34.16,
    durcisseur: 'PU 5000', prixDurcisseur: 44.13,
    ratioA: 3, ratioB: 1,
    diluant: 'V-23', prixDiluant: null,
    dilMin: 0, dilRetenue: 0.03, dilMax: 0.05,
    densite: 1.02,
    rendMin: 6, rendMax: 7, rendUnite: 'm²/L',
    statut: 'Complet - prix diluant manquant',
    notes: 'Pinceau/rouleau : V-23 si nécessaire jusqu’à env. 3 % ; 3 % retenu.',
  },
  {
    ref: '124640000-052',
    nom: 'SATIMAT teinté',
    type: '1K solvant',
    prixA: 36.61,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'V-16', prixDiluant: 13.62,
    dilMin: 0.1, dilRetenue: 0.15, dilMax: 0.2,
    densite: 1.25,
    rendMin: 7, rendMax: 9, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : 10–20 % V-16 ; 15 % retenu = milieu de plage.',
  },
  {
    ref: '124100000-052',
    nom: 'RUCOKORR satiné teinté 1 kg',
    type: '1K solvant',
    prixA: 35.3,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'V-16', prixDiluant: 13.62,
    dilMin: 0.1, dilRetenue: 0.125, dilMax: 0.15,
    densite: 1.25,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : 10–15 % V-16 ; 12,5 % retenu = milieu de plage.',
  },
  {
    ref: '124100000-054',
    nom: 'RUCOKORR satiné teinté 3 kg',
    type: '1K solvant',
    prixA: 31.68,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: 'V-16', prixDiluant: 13.62,
    dilMin: 0.1, dilRetenue: 0.125, dilMax: 0.15,
    densite: 1.25,
    rendMin: 6, rendMax: 8, rendUnite: 'm²/kg',
    statut: 'Complet',
    notes: 'Pistolet : 10–15 % V-16 ; 12,5 % retenu = milieu de plage.',
  },
  {
    ref: '124600000-052',
    nom: 'SATINA teinté',
    type: '1K solvant',
    prixA: 30.15,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: null, prixDiluant: null,
    dilMin: null, dilRetenue: null, dilMax: null,
    densite: 1.2,
    rendMin: null, rendMax: null, rendUnite: null,
    statut: 'Prix seul - FT manquante',
    notes: 'Dilution et rendement laissés vides tant que la FT SATINA n’est pas intégrée.',
  },
  {
    ref: '104200008-550',
    nom: 'RUCOLINOL imprégnation huile 4.5 L',
    type: 'Imprégnation',
    prixA: 21.3,
    durcisseur: null, prixDurcisseur: 0,
    ratioA: 1, ratioB: 0,
    diluant: null, prixDiluant: null,
    dilMin: null, dilRetenue: null, dilMax: null,
    densite: 0.9,
    rendMin: null, rendMax: null, rendUnite: null,
    statut: 'Prix seul - FT manquante',
    notes: 'Dilution et rendement laissés vides tant que la FT RUCOLINOL n’est pas intégrée.',
  },
  {
    ref: '126330000-052',
    nom: 'ATAPUR FORTE 10 mat teinté',
    type: '2K solvant',
    prixA: null,
    durcisseur: 'DD 5042', prixDurcisseur: 52.17,
    ratioA: 10, ratioB: 1,
    diluant: 'V-15', prixDiluant: 13.34,
    dilMin: null, dilRetenue: null, dilMax: null,
    densite: 1.0,
    rendMin: null, rendMax: null, rendUnite: null,
    statut: 'Prix manquant',
    notes: 'Prix facturé à 100 % de rabais sur la facture repérée ; ne pas utiliser ce zéro comme prix catalogue. Dilution/rendement à confirmer.',
  },
]

/** Index par SKU — le lien avec le catalogue technique RUCO. */
export const PRIX_PAR_REF = Object.fromEntries(PEINTURES.map(p => [p.ref, p]))

/**
 * Les références du calculateur peuvent porter deux SKU séparés par une barre
 * (« 126040/126020-052 » : même produit, deux brillances). On indexe les deux.
 */
export function chercherPrix(ref) {
  if (!ref) return null
  if (PRIX_PAR_REF[ref]) return PRIX_PAR_REF[ref]
  return PEINTURES.find(p => p.ref.split('/').some(r => r.trim() === String(ref).trim())) || null
}
